### ISSUE TITLE
minimqtt lib problem with TLS broker

### ISSUE THREAD

**Issue by kllsamui** [adafruit/circuitpython#7606]
### CircuitPython version

```python
CP800b6 daily 
Adafruit CircuitPython 8.0.0-beta.6-43-g1c1cf1cf5 on 2023-01-18; Raspberry Pi Pico W with rp2040
Board ID:raspberry_pi_pico_w
```

### Code/REPL

```python
negative number of bytes to read: -115
```

### Behavior

use: CP800b6 latest ( from 14. and 18. ) ( with bundle /lib/ from 15. and 17. )
on a PICO_W ( nuked )
to connect to a local broker ( RPI mosquitto) OK
BUT
to a remote broker TLS ( HIVEMQ ) ERROR
always get error at subscribe or publish about
negative number of bytes to read: -115

i think that comes from a recent change of minimqtt lib

++ confirm, all same but replace /lib/minimqtt/
from adafruit-circuitpython-bundle-8.x-mpy-20221221.zip
still works 

### Additional information

adafruit-circuitpython-bundle-8.x-mpy-20221221.zip 
/lib/minimqtt/
OK

**Comment by DavePutz** [comment]
Testing (with a lot of tracing) has shown that the 116 is, in fact, an  MP_ETIMEDOUT error code  being returned from lwip_tcp_receive in common-hal/socketpool/Socket.c. I am unsure why the value is 116, as MP_ETIMEDOUT is defined as 110 in py/mperrno.h. Adding a "keep_alive=100" to the MQTT initialization in the supplied script avoids the timeout in my testing. There may well be some issue here that is keeping the error from being properly reported, perhaps because at some point the return value is being passed back up the chain as an unsigned.

**Comment by vladak** [comment]
Nice work @DavePutz. For the record, the value of 115 matches `MP_EINPROGRESS` in `circuitpython/py/mperrno.h`, might be related considering the single zero byte returned from the function.

**Comment by DavePutz** [comment]
One mystery solved; the #define of ETIMEDOUT in /arm-none-eabi/include/sys/errno.h is 116. Now the question is whether that error should be returned to the user, or perhaps a retry in the minimqtt library, or maybe increase the default value for TLS connections from 60 in the library. @kllsamui , are you able to test with your original setup and verify that a keep_alive of 100 is sufficient?

**Comment by vladak** [comment]
Cool. I think in such case`recv_into` should raise an exception. The `_wait_for_msg()` will [deal with it](https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/blob/342b8c99b2c8f10b605cc8311bf5f394f4d18e92/adafruit_minimqtt/adafruit_minimqtt.py#L967-L980):
```python

        # CPython socket module contains a timeout attribute
        if hasattr(self._socket_pool, "timeout"):
            try:
                res = self._sock_exact_recv(1)
            except self._socket_pool.timeout:
                return None
        else:  # socketpool, esp32spi
            try:
                res = self._sock_exact_recv(1)
            except OSError as error:
                if error.errno in (errno.ETIMEDOUT, errno.EAGAIN):
                    # raised by a socket timeout if 0 bytes were present
                    return None
                raise MMQTTException from error
```

**Comment by kllsamui** [comment]
@DavePutz 
![Screenshot 2023-02-22 082402](https://user-images.githubusercontent.com/19226581/220496747-d92fd452-8bbd-4a01-8bc3-8da18d7b24f2.png)

**Comment by DavePutz** [comment]
@kllsamui , the value of 100 I used was based on the two MQTT brokers I had available to test (1 local, 1remote). Some sites could require even more time. The fix in PR #7623 should take care of the problem regardless of the keep_alive timeout.

**Comment by kllsamui** [comment]
@DavePutz 

try 5000
![image](https://user-images.githubusercontent.com/19226581/220514876-c255eeb6-cdb8-42f3-b3e1-627ce163f83c.png)



so i have to test the ?next? CP802++daily from 
https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix=bin/raspberry_pi_pico_w/en_US/
( the newest NOW is 2023-02-21T22:26:38 )

or look for a new /lib/adafruit__minimqtt/ bundle?

**Comment by kllsamui** [comment]
@dhalbert 
pls reopen

**Comment by kllsamui** [comment]
use 'logging' again

![image](https://user-images.githubusercontent.com/19226581/220561096-fe6878a3-f814-4a16-afc3-fb47a4db2934.png)

why it say INSECURE
```
INFO - Establishing an INSECURE connection to <xxx>.hivemq.cloud:8883
```

**Comment by kllsamui** [comment]
```
1615.053: DEBUG - waiting for messages for 0 seconds
1615.560: DEBUG - waiting for messages for 0 seconds
1616.066: DEBUG - waiting for messages for 0 seconds
1616.572: DEBUG - waiting for messages for 0 seconds
```
is meant to say 0.5 sec ?

**Comment by vladak** [comment]
INSECURE means plaintext MQTT. If you want TLS, you need to set is_ssl to True.

On Wed, Feb 22, 2023, at 09:15, KLL wrote:
> 
> 
> use 'logging' again
> 
> image <https://user-images.githubusercontent.com/19226581/220561096-fe6878a3-f814-4a16-afc3-fb47a4db2934.png>
> 
> why it say INSECURE
> 
> `INFO - Establishing an INSECURE connection to <xxx>.hivemq.cloud:8883
`

**Comment by vladak** [comment]
I think that's because default loop() timeout is 0. See issue 142 in the Adafruit MQTT project.

On Wed, Feb 22, 2023, at 09:38, KLL wrote:
> 
> 
> `1615.053: DEBUG - waiting for messages for 0 seconds
> 1615.560: DEBUG - waiting for messages for 0 seconds
> 1616.066: DEBUG - waiting for messages for 0 seconds
> 1616.572: DEBUG - waiting for messages for 0 seconds
`

**Comment by jepler** [comment]
<details>
<summary>OP's testing code</summary>

```python
# ______________________________________________________ TEST CODE for LOCAL REMOTE broker TLS problem

import time
import microcontroller
#import micropython
#import gc # micropython garbage collection # use gc.mem_free() # use gc.collect

import os # ____________________________________________ expect file: settings.toml with:
THIS_REVISION = os.getenv('THIS_REVISION')
THIS_OS = os.getenv('THIS_OS')

WIFI_SSID = os.getenv('WIFI_SSID')
WIFI_PASSWORD = os.getenv('WIFI_PASSWORD')

WIFI_IP = os.getenv('WIFI_IP')

DIAG = True # False # ___________________________________ global print disable switch / overwritten by console [D][enter]
DIAG = bool(os.getenv('DIAG')) # ________________________ now get from settings.toml

def dp(line=" ", ende="\n"):
    if DIAG : print(line, end=ende)

import socketpool
from ipaddress import ip_address
import wifi

from adafruit_httpserver.server import HTTPServer
from adafruit_httpserver.request import HTTPRequest
from adafruit_httpserver.response import HTTPResponse
from adafruit_httpserver.methods import HTTPMethod
from adafruit_httpserver.mime_type import MIMEType

dp("___ Connecting to router {:s} OR CHECK THE 'settings.toml' FILE".format( WIFI_SSID) )
wifi.radio.set_ipv4_address( # _______________________ fixIP ( requires > CP 8.0.0 beta 4 )
    ipv4=ip_address(WIFI_IP),
    netmask=ip_address("255.0.0.0"),
    gateway=ip_address("192.168.1.1"),
    ipv4_dns=ip_address("192.168.1.1"),
)
wifi.radio.connect(WIFI_SSID, WIFI_PASSWORD)
dp("___ Connected to {:s}".format( WIFI_SSID) )

dp("___ Listening on http://{:s}:80 ".format(str(wifi.radio.ipv4_address)) )

pool = socketpool.SocketPool(wifi.radio)

# make a WEB SERVER
server = HTTPServer(pool)

HtmlStyle =   '<style>'
HtmlStyle +=   'html {font-family: "Times New Roman", Times, serif; background-color: lightgreen;'
HtmlStyle +=   'display:inline-block; margin: 0px auto; text-align: center;}'
HtmlStyle +=   'h1{color: deeppink; width: 200; word-wrap: break-word; padding: 2vh; font-size: 35px;}'
HtmlStyle +=   'p{font-size: 1.5rem; width: 200; word-wrap: break-word;}'
HtmlStyle +=   '.button{font-family: {font_family};display: inline-block;'
HtmlStyle +=   'background-color: black; border: none;'
HtmlStyle +=   'border-radius: 4px; color: white; padding: 16px 40px;'
HtmlStyle +=   'text-decoration: none; font-size: 30px; margin: 2px; cursor: pointer;}'
HtmlStyle +=   'p.dotted {margin: auto; width: 75%; font-size: 25px; text-align: center;}'
HtmlStyle +=   '</style>'

def html_index_page():
    htmldata =  '<!DOCTYPE html><html><head><title>KLL Pico W Web Server</title>'
    htmldata += HtmlStyle
    htmldata += '</head><body>'
    htmldata += '<h1>KLL Pico W Web Server</h1><h2> from Circuit Python'
    htmldata += THIS_OS + '</h2>'
    htmldata += '<img src="http://kll.engineering-news.org/kllfusion01/downloads/RPI_PICO_W.png" >'
    htmldata += '<p> image PICO W </p>'
    htmldata += '<p>  <a href="http://kll.engineering-news.org/kllfusion01/articles.php?article_id=213" target="_blank" ><b>kll.engineering-news.org</b></a> rev: '
    htmldata += THIS_REVISION
    htmldata += '</p>'
    htmldata += '</body></html>'
    return htmldata

def mqtt_connect() :
    global server, mqtt_client, mqtt_topic, MQTTok, pool, use_REMOTE_broker
    if ( True ) :
        dp("___+++ setup MQTT")
        import adafruit_minimqtt.adafruit_minimqtt as MQTT
        import json
        import ssl

        MQTTok = False
        MQTT_broker = os.getenv('MQTT_broker') # ___ RPI IP
        MQTT_port = os.getenv('MQTT_port') # __ 1883
        MQTT_user = os.getenv('MQTT_user') # _______ u213
        MQTT_pass = os.getenv('MQTT_pass') # _______ p213
        MQTT_TLS = os.getenv('MQTT_TLS') # _________ "n"
        MQTT_topic = os.getenv('MQTT_topic')

        use_REMOTE_broker = os.getenv('use_REMOTE_broker')
        if ( use_REMOTE_broker == "y" ):
            MQTT_broker = os.getenv('remote_broker') # ___ HIVEMQ
            MQTT_port = os.getenv('remote_port') # __ 8883
            MQTT_user = os.getenv('remote_user') # _______
            MQTT_pass = os.getenv('remote_pass') # _______
            MQTT_TLS = os.getenv('remote_TLS') # _________ "y"
            MQTT_topic = os.getenv('remote_topic') #

        MQTT_count = 0 # _____________________________________ send to broker as id too
        mqtt_hello="Hello Broker: i am a PICO W"
        mqtt_topic = MQTT_topic
        ### MQTT Code ###
        # Define callback methods which are called when events occur
        # pylint: disable=unused-argument, redefined-outer-name
        def connect(mqtt_client, userdata, flags, rc):
            # This function will be called when the mqtt_client is connected
            # successfully to the broker.
            dp("___ Connected to MQTT Broker!")
            dp("___ Flags: {0} RC: {1}".format(flags, rc))


        def disconnect(mqtt_client, userdata, rc):
            # This method is called when the mqtt_client disconnects
            # from the broker.
            dp("___ Disconnected from MQTT Broker!")


        def subscribe(mqtt_client, userdata, topic, granted_qos):
            # This method is called when the mqtt_client subscribes to a new feed.
            dp("___ Subscribed to {0} with QOS level {1}".format(topic, granted_qos))


        def unsubscribe(mqtt_client, userdata, topic, pid):
            # This method is called when the mqtt_client unsubscribes from a feed.
            dp("___ Unsubscribed from {0} with PID {1}".format(topic, pid))


        def publish(mqtt_client, userdata, topic, pid):
            # This method is called when the mqtt_client publishes data to a feed.
            dp("___ Published to {0} with PID {1} ".format(topic, pid))


        def message(client, topic, message):
            #global Va,Vb,Aa,Ab,Wa,Wb # here overwritten
            # Method called when a client's subscribed feed has a new value.
            dp("___ New message on topic {0}: {1}".format(topic, message))
            # here evaluate REMOT COMMANDS

        ### END MQTT functions ###


        # Set up a MiniMQTT Client !! from adafruit example NOT use client name?
        # https://docs.circuitpython.org/projects/minimqtt/en/latest/api.html
        # client_id (str) – Optional client identifier, defaults to a unique, generated string.
        dp("___+++ setup MQTTclient")
        if ( MQTT_TLS == "y" ) :
            dp("___++++ use TLS")
            mqtt_client = MQTT.MQTT(
                broker=MQTT_broker,
                port=MQTT_port,
                username=MQTT_user,
                password=MQTT_pass,
                socket_pool=pool,
                ssl_context=ssl.create_default_context()
            )
        else :
            dp("___++++ NO TLS")
            mqtt_client = MQTT.MQTT(
                broker=MQTT_broker,
                port=MQTT_port,
                username=MQTT_user,
                password=MQTT_pass,
                socket_pool=pool
                #ssl_context=ssl.create_default_context(),
            )

        # Connect callback handlers to mqtt_client
        mqtt_client.on_connect = connect
        mqtt_client.on_disconnect = disconnect
        mqtt_client.on_subscribe = subscribe
        mqtt_client.on_unsubscribe = unsubscribe
        mqtt_client.on_publish = publish
        mqtt_client.on_message = message

        try:
            dp("___ Attempting to connect to %s" % mqtt_client.broker)
            mqtt_client.connect()
            MQTTok = True # _______________________________ used later for publish
        except Exception as e:
            print("Error: MQTT connect\n", str(e))
            MQTTok = False

        try:
            dp("___ Publishing to %s" % MQTT_topic) # _____ only master topic should gets that
            dp(mqtt_hello)
            mqtt_client.publish(MQTT_topic,mqtt_hello )
            MQTTok = True # _______________________________ used later for publish
        except Exception as e:
            print("Error: MQTT publish hello\n", str(e))
            #MQTTok = False

        try:
            # setup subscribe
            mqtt_topic_tune = mqtt_topic + "/set"
            dp("___ Subscribing to %s tuning" % mqtt_topic_tune)
            mqtt_client.subscribe(mqtt_topic_tune)
        except Exception as e:
            print("Error: MQTT subscribe tuning\n", str(e))
            #MQTTok = False

        dp("___ MQTT broker: "+MQTT_broker)
        dp("___ mqtt_topic: "+mqtt_topic)


@server.route("/")
def base(request):  # pylint: disable=unused-argument
    dp("\nwifi served dynamic index.html")
    response = HTTPResponse(request)
    with response:
        response.send(body=html_index_page(), content_type=MIMEType.TYPE_HTML)

server.start(str(wifi.radio.ipv4_address)) # ______________ startup the server

mqtt_connect() # __________________________________________ above MQTT start NOTE: broker must be up first



while True :
    try:
        server.poll()
    except OSError:
        print("ERROR server poll")

    try:
        mqtt_client.loop() # ______________________________ now we see the subscribed tuning come through
    except Exception as e:
        print("Error: MQTT loop\n", str(e))
        MQTTok = False
        #time.sleep(10) # __________________________________ broker reboot expected
        #microcontroller.reset() # _________________________ try reboot case broker recovered

    time.sleep(0.5)
```
</details>

**Comment by kllsamui** [comment]
no news, just for info:
* nuke
* adafruit-circuitpython-raspberry_pi_pico_w-en_US-20230222-c2c7b93.uf2
* adafruit-circuitpython-bundle-8.x-mpy-20230223.zip

works with ```is_ssl=True,```
HANGS without
```
___ Connecting to router kll-wlan_2.4G OR CHECK THE 'settings.toml' FILE
___ Connected to kll-wlan_2.4G
___ Listening on http://192.168.1.214:80 
___+++ setup MQTT
___+++ setup MQTTclient
___++++ use TLS
___ Attempting to <xxx>.hivemq.cloud
```
after several minutes wait see
```
Error: MQTT connect
 Repeated connect failures
___ Publishing to PICO_W
Hello Broker: i am a PICO W
Error: MQTT publish hello
 MiniMQTT is not connected
___ Subscribing to PICO_W/set tuning
Error: MQTT subscribe tuning
 MiniMQTT is not connected
___ MQTT broker:<xxx>hivemq.cloud
___ mqtt_topic: PICO_W
Error: MQTT loop
 Unable to receive 1 bytes within 60 seconds.
Error: MQTT loop
 MiniMQTT is not connected
```
_______________
with logging :
```
___ Connecting to router kll-wlan_2.4G OR CHECK THE 'settings.toml' FILE
___ Connected to kll-wlan_2.4G
___ Listening on http://192.168.1.214:80 
___+++ setup MQTT
___+++ setup MQTTclient
___++++ use TLS
___ Attempting to connect to <xxx>hivemq.cloud
1207.934: DEBUG - Attempting to connect to MQTT broker (attempt #0)
1207.938: DEBUG - Attempting to establish MQTT connection...
1207.943: INFO - Establishing an INSECURE connection to <xxx>.hivemq.cloud:8883
1208.250: DEBUG - Sending CONNECT to broker...
1208.254: DEBUG - Fixed Header: bytearray(b'\x10-\x00')
1208.259: DEBUG - Variable Header: bytearray(b'\x04MQTT\x04\xc2\x00<')
1208.264: DEBUG - Receiving CONNACK packet from broker
1268.272: INFO - MMQT error: Unable to receive 1 bytes within 60 seconds.
1268.277: DEBUG - Reconnect timeout computed to 2.00
1268.281: DEBUG - adding jitter 0.10 to 2.00 seconds
1268.286: DEBUG - Attempting to connect to MQTT broker (attempt #1)
1268.290: DEBUG - Attempting to establish MQTT connection...
1268.293: DEBUG - Sleeping for 2.1 seconds due to connect back-off
1270.399: INFO - Establishing an INSECURE connection to <xxx>hivemq.cloud:8883
1270.707: DEBUG - Sending CONNECT to broker...
1270.711: DEBUG - Fixed Header: bytearray(b'\x10-\x00')
1270.715: DEBUG - Variable Header: bytearray(b'\x04MQTT\x04\xc2\x00<')
1270.720: DEBUG - Receiving CONNACK packet from broker
1330.729: INFO - MMQT error: Unable to receive 1 bytes within 60 seconds.
1330.734: DEBUG - Reconnect timeout computed to 4.00
1330.738: DEBUG - adding jitter 0.39 to 4.00 seconds
1330.742: DEBUG - Attempting to connect to MQTT broker (attempt #2)
1330.746: DEBUG - Attempting to establish MQTT connection...
1330.750: DEBUG - Sleeping for 4.39 seconds due to connect back-off
1335.145: INFO - Establishing an INSECURE connection to <xxx>hivemq.cloud:8883
1335.453: DEBUG - Sending CONNECT to broker...
1335.458: DEBUG - Fixed Header: bytearray(b'\x10-\x00')
1335.462: DEBUG - Variable Header: bytearray(b'\x04MQTT\x04\xc2\x00<')
1335.467: DEBUG - Receiving CONNACK packet from broker
1395.475: INFO - MMQT error: Unable to receive 1 bytes within 60 seconds.
1395.480: DEBUG - Reconnect timeout computed to 8.00
1395.484: DEBUG - adding jitter 0.91 to 8.00 seconds
1395.489: DEBUG - Attempting to connect to MQTT broker (attempt #3)
1395.492: DEBUG - Attempting to establish MQTT connection...
1395.497: DEBUG - Sleeping for 8.91 seconds due to connect back-off
1404.417: INFO - Establishing an INSECURE connection to 01d9986933e64070a549e134b27cd218.s2.eu.hivemq.cloud:8883
1404.723: DEBUG - Sending CONNECT to broker...
1404.728: DEBUG - Fixed Header: bytearray(b'\x10-\x00')
1404.733: DEBUG - Variable Header: bytearray(b'\x04MQTT\x04\xc2\x00<')
1404.738: DEBUG - Receiving CONNACK packet from broker
1464.746: INFO - MMQT error: Unable to receive 1 bytes within 60 seconds.
1464.750: DEBUG - Reconnect timeout computed to 16.00
1464.754: DEBUG - adding jitter 0.12 to 16.00 seconds
1464.758: DEBUG - Attempting to connect to MQTT broker (attempt #4)
1464.762: DEBUG - Attempting to establish MQTT connection...
1464.766: DEBUG - Sleeping for 16.1 seconds due to connect back-off
1480.895: INFO - Establishing an INSECURE connection to 01d9986933e64070a549e134b27cd218.s2.eu.hivemq.cloud:8883
1481.201: DEBUG - Sending CONNECT to broker...
1481.206: DEBUG - Fixed Header: bytearray(b'\x10-\x00')
1481.210: DEBUG - Variable Header: bytearray(b'\x04MQTT\x04\xc2\x00<')
1481.215: DEBUG - Receiving CONNACK packet from broker
1541.223: INFO - MMQT error: Unable to receive 1 bytes within 60 seconds.
Error: MQTT connect
 Repeated connect failures
___ Publishing to PICO_W
Hello Broker: i am a PICO W
Error: MQTT publish hello
 MiniMQTT is not connected
___ Subscribing to PICO_W/set tuning
Error: MQTT subscribe tuning
 MiniMQTT is not connected
___ MQTT broker: 01d9986933e64070a549e134b27cd218.s2.eu.hivemq.cloud
___ mqtt_topic: PICO_W
1541.238: DEBUG - waiting for messages for 0 seconds
Error: MQTT loop
 Unable to receive 1 bytes within 60 seconds.
1601.748: DEBUG - waiting for messages for 0 seconds
1601.751: DEBUG - KeepAlive period elapsed - requesting a PINGRESP from the server...
Error: MQTT loop
 MiniMQTT is not connected
1602.259: DEBUG - waiting for messages for 0 seconds
Error: MQTT loop
 Unable to receive 1 bytes within 60 seconds.
1662.770: DEBUG - waiting for messages for 0 seconds
1662.774: DEBUG - KeepAlive period elapsed - requesting a PINGRESP from the server...
Error: MQTT loop
 MiniMQTT is not connected
1663.282: DEBUG - waiting for messages for 0 seconds

```
**does not the broker send a info that the login failed / connection was refused / ?**

so here again WITH ```is_ssl = True``` and logging

```
___ Connecting to router kll-wlan_2.4G OR CHECK THE 'settings.toml' FILE
___ Connected to kll-wlan_2.4G
___ Listening on http://192.168.1.214:80 
___+++ setup MQTT
___+++ setup MQTTclient
___++++ use TLS
___ Attempting to connect to <xxx>hivemq.cloud
2641.719: DEBUG - Attempting to connect to MQTT broker (attempt #0)
2641.723: DEBUG - Attempting to establish MQTT connection...
2641.728: INFO - Establishing a SECURE SSL connection to <xxx>hivemq.cloud:8883
2645.262: DEBUG - Sending CONNECT to broker...
2645.268: DEBUG - Fixed Header: bytearray(b'\x10.\x00')
2645.272: DEBUG - Variable Header: bytearray(b'\x04MQTT\x04\xc2\x00<')
2645.282: DEBUG - Receiving CONNACK packet from broker
___ Connected to MQTT Broker!
___ Flags: 0 RC: 0
2645.850: DEBUG - Resetting reconnect backoff
___ Publishing to PICO_W
Hello Broker: i am a PICO W
2645.857: DEBUG - Sending PUBLISH
Topic: PICO_W
Msg: b'Hello Broker: i am a PICO W'                            
QoS: 0
Retain? False
___ Published to PICO_W with PID 0 
___ Subscribing to PICO_W/set tuning
2645.873: DEBUG - SUBSCRIBING to topic PICO_W/set with QoS 0
___ Subscribed to PICO_W/set with QOS level 0
___ MQTT broker:<xxx>hivemq.cloud
___ mqtt_topic: PICO_W
2646.419: DEBUG - waiting for messages for 0 seconds
2646.925: DEBUG - waiting for messages for 0 seconds
2647.433: DEBUG - waiting for messages for 0 seconds
```

pls see that actually in booth cases there is a
```
Receiving CONNACK packet from broker
```
i am confused...

**Comment by dhalbert** [comment]
We believe this is fixed by #7632.

**Comment by jepler** [comment]
from what I can see, hivemq only offers mqtt over tls (what we call is_ssl=True). It's no surprise if they can't successfully communicate when one side is expecting TLS and the other is expecting plaintext.

![image](https://user-images.githubusercontent.com/1517291/220933454-6c6e90bd-e1fd-441a-b96e-8dff433ca162.png)

**Comment by jepler** [comment]
Port 1883 is allocated for non-secure MQTT. However, hivemq machines do not respond on port 1883. I think that non-TLS (use_ssl=False) is not supported by hivemq.

**Comment by berarduc** [comment]
Has this issue been fixed? I'm using latest 8.2 circuitpython and minimqtt library and this problem still occurs.

**Comment by vladak** [comment]
> Has this issue been fixed? I'm using latest 8.2 circuitpython and minimqtt library and this problem still occurs.
> 

This issue is closed, so it would be better to open new one, describe your problem in detail and reference this issue.
