### ISSUE TITLE
Corrupted FS when writing to SD Card

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#847]
executing this code has repeatedly resulted in a corrupted FS with teh current master CP 3.0
It often fails to allocate enough memory, but sometime runs. If it does all seem ok for awhile -then the FS seem to just disappear.... 
I have reproduced this on a feather_m0_express and on a feather_m0_supersized.
Both with a featherwing Adalogger attached.

```
# Initialize and mount SD card of Featherboard adalogger
import board
import busio
import digitalio
import adafruit_pcf8523
import adafruit_sdcard
import storage
import adafruit_dht

# create the SPI bus and a digital output for the microSD card's c\s line
spi = busio.SPI(board.SCK, MOSI=board.MOSI, MISO=board.MISO)
cs = digitalio.DigitalInOut(board.D5)


# create the microSD card object and the filesystem object
sdcard = adafruit_sdcard.SDCard(spi, cs)
vfs = storage.VfsFat(sdcard)

# mount the microSD card's filesystem into the CircuitPython filesystem
storage.mount(vfs, "/sd")

# Now ready to read and write data from the sd card
with open("/sd/test.txt", "w") as f:
    f.write("Hello world!\r\n")

# open a file and read a line from it with similar code
with open("/sd/test.txt", "r") as f:
    print("Read line from file:")
    print(f.readline())

```

**Comment by jerryneedell** [comment]
The FS appears to remain OK until the next soft reboot of the system after execution of the code.
Whe it reboots, the CIRCUITPY drive no longer appears on my Ubuntu linux system- It reamied connected to the REPL but if I then try 
import os
os.listdir()
it hangs and I have to physically reboot but the system is no longer responsive and I have to upload the eraser .uf2  to recover.

**Comment by jerryneedell** [comment]
interestingly - another program that writes to the SDCard runs with no ill effect 

```
import time
import board
import busio
import adafruit_am2320
import adafruit_sdcard
import digitalio
import storage

# can also use board.SDA and board.SCL for neater looking code!
i2c = busio.I2C(board.SCL, board.SDA)
am2320 = adafruit_am2320.AM2320(i2c)


# Connect to the card and mount the filesystem.
spi = busio.SPI(board.SCK, board.MOSI, board.MISO)
cs = digitalio.DigitalInOut(board.D5)
sdcard = adafruit_sdcard.SDCard(spi, cs)
sdc = storage.VfsFat(sdcard)
storage.mount(sdc, "/sd_card")

while True:
    try:
       with open("/sd_card/log.txt", "a") as sdc:
            temperature = am2320.temperature
            humidity = am2320.relative_humidity
            print("Temperature:", temperature)
            print("Humidity:", humidity)
            sdc.write("{},{}\n".format(temperature,humidity))
            sdc.flush()
            time.sleep(3)
    except OSError:
        print("OSError reported")
        # These sensors are a bit flakey, its ok if the readings fail
        pass
    except RuntimeError:
        print("RunTime reported")
        pass
    time.sleep(2)
```

**Comment by jerryneedell** [comment]
I can run this with no problem

```
jerryneedell@Ubuntu-Macmini:~/projects/feather_m0_express$ cat sdtest.py 
import adafruit_sdcard
import busio
import digitalio
import board
import storage

# Connect to the card and mount the filesystem.
spi = busio.SPI(board.SCK, board.MOSI, board.MISO)
cs = digitalio.DigitalInOut(board.D5)
sdcard = adafruit_sdcard.SDCard(spi, cs)
vfs = storage.VfsFat(sdcard)
storage.mount(vfs, "/sd")

# Use the filesystem as normal.
with open("/sd/test.txt", "w") as f:
    f.write("Hello world\n")
# open a file and read a line from it with similar code
with open("/sd/test.txt", "r") as f:
    print("Read line from file:")
    print(f.readline())
```

**Comment by jerryneedell** [comment]
causing the FS corruption by executing the code listed in the firs message is very reproducible on a feather_m0_express.  I'm confused....

**Comment by jerryneedell** [comment]
I remove the import dht from the test code and it still causes the same problems.
Sometimes it cannot allocate enough memory an fails.
Sometimes is runs to completion - and corrupts the FS.
Could the problem be due to being very low on available RAM when accessing h SD-Card.Still it is not the SD Card that gets corrupted, it is the CiRCUITPY FS.

**Comment by jerryneedell** [comment]
one more test case -- running this seems to execute OK and I can do a soft reboot, BUT at the next hard reset/power cycle, the FS is corrupted - I cant even get to REPL
```
import adafruit_sdcard
import busio
import digitalio
import board
import storage

# Connect to the card and mount the filesystem.
spi = busio.SPI(board.SCK, board.MOSI, board.MISO)
cs = digitalio.DigitalInOut(board.D5)
sdcard = adafruit_sdcard.SDCard(spi, cs)
vfs = storage.VfsFat(sdcard)
storage.mount(vfs, "/sd")

# Use the filesystem as normal.
with open("/sd/test.txt", "w") as f:
    f.write("Hello world\n")
# open a file and read a line from it with similar code
with open("/sd/test.txt", "r") as f:
    print("Read line from file:")
    print(f.readline())

```

**Comment by deshipu** [comment]
Wait a minute, filesystem corruption shouldn't affect REPL...

**Comment by jerryneedell** [comment]
Yikes -- something very odd is going on -- much of the above may be just red-herrings...
I just tried erasing the FS  on the feather_m0_express-- load the erase .uf2
then reload CP  -- looks good - I get to REPL.
Power cycle and the FS is corrupted again..

**Comment by deshipu** [comment]
I don't know if that's related, but I recently had some problems flashing the uf2 of the master — it would work the first time, but then flashing the same or similar image (with different frozen code) would result in a crash — not even USB or REPL visible — until I flash some completely different image (for example 2.x) and re-flash the master.

**Comment by deshipu** [comment]
In my case that was on the µGame, so it's my own build of some really old version of the bootloader. Was there some change in 3.x that made it incompatible with the old bootloaders?

**Comment by jerryneedell** [comment]
```
UF2 Bootloader v1.21.0 SFHR
Model: Feather M0
Board-ID: SAMD21G18A-Feather-v0
```
I'll try updating

**Comment by dhalbert** [comment]
@deshipu I'm just trying to eliminate some possibilities. Also, the clock code for the SAMD21 was redone about 10 days ago with https://github.com/adafruit/circuitpython/pull/785. If either of you can reproduce the problem consistently, we can bisect to see if that (or something else) is causing a problem.

**Comment by jerryneedell** [comment]
updating  bootloader did not help - in fact I then loaded current master and I could not even get to REPL or mount the FS.. I reverted to the released alpha6 and it is working fine.

**Comment by jerryneedell** [comment]
I then reloaded current master and REPL was OK but after power cycle -it is gone again

**Comment by jerryneedell** [comment]
should I try removing #785?

**Comment by dhalbert** [comment]
@jerryneedell sure

**Comment by jerryneedell** [comment]
hmmm -- cant revert it -- not sure what the conflicts are:
```
jerryneedell@Ubuntu-Macmini:~/projects/adafruit_github/circuitpython_master$ git checkout -b revert_785
Switched to a new branch 'revert_785'
jerryneedell@Ubuntu-Macmini:~/projects/adafruit_github/circuitpython_master$ git revert -m 1 d3a5d40
error: could not revert d3a5d40... Merge pull request #785 from notro/rtc_calibration
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
```

**Comment by jerryneedell** [comment]
after trying th above revert - git diff shows:
```
jerryneedell@Ubuntu-Macmini:~/projects/adafruit_github/circuitpython_master$ git diff
diff --cc ports/atmel-samd/boards/feather_m0_express/mpconfigboard.h
index bfa8c64,56e9c8b..0000000
--- a/ports/atmel-samd/boards/feather_m0_express/mpconfigboard.h
+++ b/ports/atmel-samd/boards/feather_m0_express/mpconfigboard.h
@@@ -46,15 -46,3 +46,18 @@@
                                 GD25Q16C
  
  #include "external_flash/external_flash.h"
++<<<<<<< HEAD
 +
 +#define BOARD_HAS_CRYSTAL 1
 +
 +#define DEFAULT_I2C_BUS_SCL (&pin_PA23)
 +#define DEFAULT_I2C_BUS_SDA (&pin_PA22)
 +
 +#define DEFAULT_SPI_BUS_SCK (&pin_PB11)
 +#define DEFAULT_SPI_BUS_MOSI (&pin_PB10)
 +#define DEFAULT_SPI_BUS_MISO (&pin_PA12)
 +
 +#define DEFAULT_UART_BUS_RX (&pin_PA11)
 +#define DEFAULT_UART_BUS_TX (&pin_PA10)
++=======
++>>>>>>> parent of d3a5d40... Merge pull request #785 from notro/rtc_calibration
diff --cc ports/atmel-samd/boards/metro_m0_express/mpconfigboard.h
index f798c5d,a433e99..0000000
--- a/ports/atmel-samd/boards/metro_m0_express/mpconfigboard.h
+++ b/ports/atmel-samd/boards/metro_m0_express/mpconfigboard.h
@@@ -47,15 -47,3 +47,18 @@@
                                 GD25Q16C
  
  #include "external_flash/external_flash.h"
++<<<<<<< HEAD
 +
 +#define BOARD_HAS_CRYSTAL 1
 +
 +#define DEFAULT_I2C_BUS_SCL (&pin_PA23)
 +#define DEFAULT_I2C_BUS_SDA (&pin_PA22)
 +
 +#define DEFAULT_SPI_BUS_SCK (&pin_PB11)
 +#define DEFAULT_SPI_BUS_MOSI (&pin_PB10)
 +#define DEFAULT_SPI_BUS_MISO (&pin_PA12)
 +
 +#define DEFAULT_UART_BUS_RX (&pin_PA11)
 +#define DEFAULT_UART_BUS_TX (&pin_PA10)
++=======
++>>>>>>> parent of d3a5d40... Merge pull request #785 from notro/rtc_calibration
```

**Comment by jerryneedell** [comment]
reverted to commit 64bd95ea0155834c2c4313c4137af198890a59bc  which was the one previous to merging #785  -- seems to be working OK

**Comment by jerryneedell** [comment]
And with thsi commit  -- the previous issues with writing to the SDCARD are resolved!!!

The case that corrupted the system repeatedly now works.

There have been a lot of commits since #785 that are not in place now, but  this is a big improvement!!

**Comment by notro** [comment]
PR #785 introduces 3 clock changes:

1. It enables OSC32K: https://github.com/adafruit/circuitpython/pull/785/commits/f21c2494cb612b9f9316ab97096e55ab30a404b4

2. It reworks the samd21 clock setup: https://github.com/adafruit/circuitpython/commit/4adba515695eb4eddf994c6847a5b92cffed6c07
AFAICT this didn't change clock register values. This snippet reverts that change:
```diff
diff --git a/ports/atmel-samd/supervisor/port.c b/ports/atmel-samd/supervisor/port.c
index 8e6f2b185..103f39c75 100644
--- a/ports/atmel-samd/supervisor/port.c
+++ b/ports/atmel-samd/supervisor/port.c
@@ -177,14 +177,8 @@ safe_mode_t port_init(void) {
     }
 #endif

-#ifdef SAMD21
-    hri_nvmctrl_set_CTRLB_RWS_bf(NVMCTRL, 2);
-    _pm_init();
-    clock_init();
-#endif
-#ifdef SAMD51
     init_mcu();
-#endif
+
     board_init();

     // Configure millisecond timer initialization.
```

3. It enables the crystal as the source for clock generator 2: https://github.com/adafruit/circuitpython/commit/2893e795fcbe0b36313a409d7d994880a3602689
This snippet disables that:
```diff
diff --git a/ports/atmel-samd/boards/feather_m0_express/mpconfigboard.h b/ports/atmel-samd/boards/feather_m0_express/mpconfigboard.h
index bfa8c642a..ee8a9c62b 100644
--- a/ports/atmel-samd/boards/feather_m0_express/mpconfigboard.h
+++ b/ports/atmel-samd/boards/feather_m0_express/mpconfigboard.h
@@ -47,8 +47,6 @@

 #include "external_flash/external_flash.h"

-#define BOARD_HAS_CRYSTAL 1
-
 #define DEFAULT_I2C_BUS_SCL (&pin_PA23)
 #define DEFAULT_I2C_BUS_SDA (&pin_PA22)
```

If you revert number 2 it also disables 3.

I'll see if I can replicate your problem later today.

**Comment by jerryneedell** [comment]
I tried the changes above on the current master:
```
jerryneedell@Ubuntu-Macmini:~/projects/adafruit_github/circuitpython_master/ports/atmel-samd$ git diff
diff --git a/ports/atmel-samd/boards/feather_m0_express/mpconfigboard.h b/ports/atmel-samd/boards/feather_m0_express/mpconfigboard.h
index bfa8c64..cfe1919 100644
--- a/ports/atmel-samd/boards/feather_m0_express/mpconfigboard.h
+++ b/ports/atmel-samd/boards/feather_m0_express/mpconfigboard.h
@@ -47,7 +47,6 @@
 
 #include "external_flash/external_flash.h"
 
-#define BOARD_HAS_CRYSTAL 1
 
 #define DEFAULT_I2C_BUS_SCL (&pin_PA23)
 #define DEFAULT_I2C_BUS_SDA (&pin_PA22)
diff --git a/ports/atmel-samd/supervisor/port.c b/ports/atmel-samd/supervisor/port.c
index 8e6f2b1..a91165e 100644
--- a/ports/atmel-samd/supervisor/port.c
+++ b/ports/atmel-samd/supervisor/port.c
@@ -177,14 +177,7 @@ safe_mode_t port_init(void) {
     }
 #endif
 
-#ifdef SAMD21
-    hri_nvmctrl_set_CTRLB_RWS_bf(NVMCTRL, 2);
-    _pm_init();
-    clock_init();
-#endif
-#ifdef SAMD51
     init_mcu();
-#endif
     board_init();
 
     // Configure millisecond timer initialization.
```
but it still fails to reboot after power cycel

**Comment by notro** [comment]
I couldn't find a sd card breakout board to hook up to my feather M0 express, so I tried a M0 Adalogger I had, but I only get: ```OSError: no SD card```
So I'm unable to try and reproduce this :-/

**Comment by jerryneedell** [comment]
I am trying to do a "bisect" to find the commit that caused the problem and I think it is well beyond yours.  Are you using the current master now?

**Comment by jerryneedell** [comment]
my attemp at a bisect gas identified this:
```
2c067edf540fcc1f1f4aa68f0992ce8480a954bb is the first bad commit
commit 2c067edf540fcc1f1f4aa68f0992ce8480a954bb
Author: Matt Land <mland@sparefoot.com>
Date:   Wed May 16 15:54:01 2018 -0400

    used pins.c instead of README.rst

:040000 040000 05f72a171e17efa3a33447fa3b571af3a2decdb5 2a454fbb36bb964794fd4c5830b2d630851b0f2f M	ports
```

**Comment by jerryneedell** [comment]
not convinced - tried previous commit to this and it still fails....

**Comment by jerryneedell** [comment]
narrowing it down -- this commit seem to work 99e34e38eb6a81e0722b31b085c2f24ea1111981

**Comment by notro** [comment]
> Are you using the current master now?

Yes.

Are you having problems on a Feather M0 Express without any code.py, from cold boot to the REPL?
Or do you get problems after some python code has run first?

**Comment by jerryneedell** [comment]
and this commit is OK 07c0a3227da24ef92e44a2457f94af71cc7f081c

@notro yes - the problem is on a clean flash - no code.py - I get no prompt from REPL and the hos OS eventually drops the USB connection to it.

**Comment by jerryneedell** [comment]
but this one fails  -- 6a8db03ade64bd2fdf5c7b5df54ad113a062e005
I was just walking up the merged PRs  --this was #838

**Comment by notro** [comment]
I'm working on Windows 10 and I just did a test connecting the board to a Raspberry Pi and it still worked.
Do you have another computer than the Mac/Ubuntu to test with?

**Comment by jerryneedell** [comment]
I "tried" removing PR#838 from the current master, but the revert did not work so Idon't trust my resut - with failed but reverting to 07c0a3227da24ef92e44a2457f94af71cc7f081c  works consistently.

@notro since my system works on some commits and not others I don't think it is the problem.
Are you using the current master now - or your last commit. I think you last commit is just fine.

**Comment by notro** [comment]
I'm using current master:
```
$ git log --oneline -1
1eb412b44 (HEAD -> test, tag: patchbase, origin/master, origin/HEAD, master) Merge pull request #845 from matt-land/feature-default-serial
```

**Comment by jerryneedell** [comment]
just tried build of master - same version as you -- it inatillay boots to REPL after load, then after power cycle it failed on the Ubuntu system, my MACOS system and my raspberry PI.
I'm puzzled!...

**Comment by jerryneedell** [comment]
as on the trinket, I can connect and the Nepoixel goes from green to white, but no REPL prompt..

**Comment by notro** [comment]
Can you upload a failing *feather_m0_express* firmware somewhere so I can try it?
This is the one I'm currently trying: http://tronnes.org/downloads/feather_m0_express-firmware.uf2

**Comment by jerryneedell** [comment]
I just tried yours and it seems to work!!!  very odd -- send mine in a minute

**Comment by jerryneedell** [comment]
here is my failing version
[feather_m0_express.zip](https://github.com/adafruit/circuitpython/files/2018374/feather_m0_express.zip)

**Comment by notro** [comment]
First soft reboot after upload gives repl, power cycling gives: Failed to recognize usb device. Same as you.

But now I have the same problem with a new build I just did! What is going on here?
Reverting to the one I sent you, is working.

**Comment by jerryneedell** [comment]
@notro -- I guess I'm relieved - a bit....

**Comment by jerryneedell** [comment]
can you reproduce the one you sent me, was it build today or ealrier?

**Comment by notro** [comment]
The one I sent you was built 1 hour ago. I'm doing a fresh build now. This is mysterious, I'm starting to doubt my own sanity :-)

**Comment by jerryneedell** [comment]
I've been doubting mine all day!  I made a new clone of the repo this morning and have been working with that.  I still can get back to a working version consistently by revering back before  PR#838

**Comment by notro** [comment]
This is the strangest thing.

Looks like I've found a reproduceable way of flipping back and forth between working and not working.
I have a build script that creates a git tag when checking out the code so I can easily dump out the commits I've done using ```git format-patch patchbase..HEAD```.


So with that tag I get a firmware that can handle power cycling:

git tagging:
```
pi@agl:~/circuitpython/workdirs/test/circuitpython$ git tag patchbase
pi@agl:~/circuitpython/workdirs/test/circuitpython$ git log --oneline -1
1eb412b44 (HEAD -> test, tag: patchbase, origin/master, origin/HEAD, master) Merge pull request #845 from matt-land/feature-default-serial
```

(re)Build:
```
pi@agl:~/circuitpython$ rake compile
cd /home/pi/circuitpython/workdirs/test/circuitpython/ports/atmel-samd
make BOARD=feather_m0_express CROSS_COMPILE=/home/pi/opt/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
Generating build-feather_m0_express/genhdr/mpversion.h
QSTR not updated
../../shared-bindings/usb_hid/__init__.h:33:23: warning: size of 'common_hal_usb_hid_devices' differ from the size of original declaration [-Wlto-type-mismatch]
 extern mp_obj_tuple_t common_hal_usb_hid_devices;
                       ^
common-hal/usb_hid/__init__.c:127:16: note: 'common_hal_usb_hid_devices' was previously declared here
 mp_obj_tuple_t common_hal_usb_hid_devices = {
                ^

33932 bytes free in flash out of 253696 bytes ( 247.75 kb ).
3936 bytes free in ram for stack out of 32768 bytes ( 32.0 kb ).

Create build-feather_m0_express/firmware.bin
Create build-feather_m0_express/firmware.uf2
../../tools/uf2/utils/uf2conv.py -b 0x2000 -c -o build-feather_m0_express/firmware.uf2 build-feather_m0_express/firmware.bin
Converting to uf2, output size: 439808, start address: 0x2000
Wrote 439808 bytes to build-feather_m0_express/firmware.uf2.
cd -
```

Board REPL, the tag show up:
```
Adafruit CircuitPython patchbase-dirty on 2018-05-18; Adafruit Feather M0 Express with samd21g18
>>>
```


Next I remove the tag and rebuild, and it can't handle power cycling:
```
pi@agl:~/circuitpython/workdirs/test/circuitpython$ git tag -d patchbase
Deleted tag 'patchbase' (was 1eb412b44)
pi@agl:~/circuitpython/workdirs/test/circuitpython$ git log --oneline -1
1eb412b44 (HEAD -> test, origin/master, origin/HEAD, master) Merge pull request #845 from matt-land/feature-default-serial
```

Build:
```
pi@agl:~/circuitpython$ rake compile
cd /home/pi/circuitpython/workdirs/test/circuitpython/ports/atmel-samd
make BOARD=feather_m0_express CROSS_COMPILE=/home/pi/opt/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
Generating build-feather_m0_express/genhdr/mpversion.h
QSTR not updated
../../shared-bindings/usb_hid/__init__.h:33:23: warning: size of 'common_hal_usb_hid_devices' differ from the size of original declaration [-Wlto-type-mismatch]
 extern mp_obj_tuple_t common_hal_usb_hid_devices;
                       ^
common-hal/usb_hid/__init__.c:127:16: note: 'common_hal_usb_hid_devices' was previously declared here
 mp_obj_tuple_t common_hal_usb_hid_devices = {
                ^

33884 bytes free in flash out of 253696 bytes ( 247.75 kb ).
3936 bytes free in ram for stack out of 32768 bytes ( 32.0 kb ).

Create build-feather_m0_express/firmware.bin
Create build-feather_m0_express/firmware.uf2
../../tools/uf2/utils/uf2conv.py -b 0x2000 -c -o build-feather_m0_express/firmware.uf2 build-feather_m0_express/firmware.bin
Converting to uf2, output size: 439808, start address: 0x2000
Wrote 439808 bytes to build-feather_m0_express/firmware.uf2.
cd -
```

REPL, no tag instead commit ref:
```
Adafruit CircuitPython 3.0.0-alpha.6-142-g1eb412b44-dirty on 2018-05-18; Adafruit Feather M0 Express with samd21g18
>>>
```

**Comment by dhalbert** [comment]
When the version string changes `boot_out.txt` is rewritten to include the new version string. The file is read first to see if the string is the same. If the version string doesn't change then it's not rewritten.

Also your tag made the string shorter, though that doesn't seem so likely an issue.

**Comment by rhooper** [comment]
@jerryneedell If you include PR #838 does it fail?

**Comment by dhalbert** [comment]
I'd suggest trying multiple times with the same build to see if it fails repeatedly, or whether you're cycling through a "first time only" effect.

**Comment by rhooper** [comment]
With master on a trinket_m0, this happened to me too.  First reboot after flashing was OK.  Second boot was not.  Starting a bisect too.

**Comment by jerryneedell** [comment]
@dhalbert for me once it fails -multiple power cycles does not bring it back.

**Comment by notro** [comment]
I have tried writing the failing firmware 3 times without any changes. I've checked that ```boot_out.txt``` gets updated.

Can it be some kind of offset problem? The flash size changes for me between working and not working.

What about this warning?
```
../../shared-bindings/usb_hid/__init__.h:33:23: warning: size of 'common_hal_usb_hid_devices' differ from the size of original declaration [-Wlto-type-mismatch]
 extern mp_obj_tuple_t common_hal_usb_hid_devices;
                       ^
common-hal/usb_hid/__init__.c:127:16: note: 'common_hal_usb_hid_devices' was previously declared here
 mp_obj_tuple_t common_hal_usb_hid_devices = {
```

**Comment by jerryneedell** [comment]
@rhooper good idea - now I just need to figure out haw to add a PR to a "detached" branch...

**Comment by dhalbert** [comment]
@notro That warning is innocuous: it's a spurious warning due to `-flto` not knowing how to match an array in a struct properly. It has been fixed upstream.

**Comment by rhooper** [comment]
Wow, it does fail reliably after #838 is merged, which reduces the flash size on trinket_m0 and gemma_m0.  I'm going to cherry-pick out all of the reload code in 838 in a branch and see what happens.

**Comment by jerryneedell** [comment]
@rhooper yes- that is waht I just found adding #838 to my working version causes it to fail. At lest I think that is what I did. I did:
```
git checkout 07c0a3227da24ef92e44a2457f94af71cc7f081c
```
this builds a working version
then I
```
jerryneedell@Ubuntu-Macmini:~/projects/adafruit_github/circuitpython_master/ports/atmel-samd$ git fetch origin pull/838/head:jerryn_test838
From https://github.com/adafruit/circuitpython
 * [new ref]         refs/pull/838/head -> jerryn_test838
jerryneedell@Ubuntu-Macmini:~/projects/adafruit_github/circuitpython_master/ports/atmel-samd$ git branch
* (HEAD detached at 07c0a32)
  jerryn_clocks
  jerryn_test838
  master
  revert_838
jerryneedell@Ubuntu-Macmini:~/projects/adafruit_github/circuitpython_master/ports/atmel-samd$ git checkout jerryn_test838
Previous HEAD position was 07c0a32... Merge pull request #843 from jerryneedell/jerryn_errno
Switched to branch 'jerryn_test838'
```
this build fails

**Comment by rhooper** [comment]
Another observation is that my main.py was still present when I flashed a good firmware.  I have pushed two different branches that revert #838:
- https://github.com/rhooper/circuitpython/tree/no-reload-patch
- https://github.com/rhooper/circuitpython/tree/no-space-savings

However these leave the flash image too big for trinket_m0 and gemma_m0 so I can't test if either of these branches work.

**Comment by jerryneedell** [comment]
I'm not git-savvy enough to know how to get those commits into my clone of master.

**Comment by dhalbert** [comment]
@rhooper you can shrink the image somewhat by uncommenting
```
    ## CFLAGS += -finline-limit=50
```
in the Makefile

**Comment by rhooper** [comment]
@jerryneedell 
```
git remote add rhooper git@github.com:rhooper/circuitpython.git
git fetch rhooper
git checkout rhooper/no-space-savings
```

**Comment by dhalbert** [comment]
@jerryneedell or just clone it fresh: `git clone https://github.com/rhooper/circuitpython rh-circuitpython` or similar

**Comment by rhooper** [comment]
@dhalbert `CFLAGS += -finline-limit=50` worked to reduce the image, but still fails to run after a hard reset or reboot.  going to seek out the most recent working commit like others.

**Comment by jerryneedell** [comment]
@rhooper cloned your repo and checked out no-space-savings  - it still fails after power cycle on the feather_m0_express

**Comment by jerryneedell** [comment]
just to get this "on the record" DEBUG builds appear to work better, but not so much.

ON a feather_mo_express and Metro_m0_express, I did a DEBUG=1 build of master and at first it seemed to work, but the REPL is not able to acces the FileSystem even though it  is visible to the OS as CIRCUITPY. In this case on Metro_m0_express there isa file sdtest.py on the FS and at first is shows up via os.listdir(), but it fails when it tries to load libraries and afterword the FS looks empty.

You can't make this stuff up....

```
Adafruit CircuitPython 3.0.0-alpha.6-142-g1eb412b on 2018-05-18; Adafruit Metro M0 Express with samd21g18
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> import os
>>> os.listdir()
['.fseventsd', '.metadata_never_index', '.Trashes', 'boot_out.txt', 'oled_test.py', 'jewel.py', 'lib', 'si7021_test.py', 'sgp30_test.py']
>>> import oled_test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "oled_test.py", line 6, in <module>
  File "adafruit_ssd1306.py", line 34, in <module>
ImportError: no module named 'adafruit_bus_device'
>>> os.listdir()
[]
>>> os.listdir()
```

**Comment by rhooper** [comment]
After spending a lot of time doing print-debugging using colours on the dotstar on trinket_m0, the hang is during maybe_run_list() during 
```
    mp_hal_stdout_tx_str(filename);
```

```
bool maybe_run_list(const char ** filenames, pyexec_result_t* exec_result) {
    const char* filename = first_existing_file_in_list(filenames);
    if (filename == NULL) {
        new_status_color(RED);
        return false;
    }
    new_status_color(BLUE);
    mp_hal_stdout_tx_str(filename);
    new_status_color(YELLOW);
    mp_hal_stdout_tx_str(MSG_OUTPUT_SUFFIX);
    new_status_color(ORANGE);
    pyexec_file(filename, exec_result);
    new_status_color(GREEN);
    return true;
}
```
halts while blue.

**Comment by rhooper** [comment]
same on gemma_m0

**Comment by rhooper** [comment]
Also, commenting out 
```
    mp_hal_stdout_tx_str(filename);
    mp_hal_stdout_tx_str(MSG_OUTPUT_SUFFIX);
```
Fixed my gemma_m0 and trinket_m0

**Comment by jerryneedell** [comment]
this reminded me of an issue a few days ago with the boot_out.txt creation.
this change creates a working version on the metro_m0_express:
```
diff --git a/ports/atmel-samd/mpconfigport.h b/ports/atmel-samd/mpconfigport.h
index 27c2480..589a7e1 100644
--- a/ports/atmel-samd/mpconfigport.h
+++ b/ports/atmel-samd/mpconfigport.h
@@ -280,6 +280,6 @@ void run_background_tasks(void);
 #define MICROPY_VM_HOOK_RETURN run_background_tasks();
 
 #define CIRCUITPY_AUTORELOAD_DELAY_MS 500
-#define CIRCUITPY_BOOT_OUTPUT_FILE "/boot_out.txt"
+//#define CIRCUITPY_BOOT_OUTPUT_FILE "/boot_out.txt"
 
 #endif  // __INCLUDED_MPCONFIGPORT_H
```

**Comment by jerryneedell** [comment]
Commenting out 
```
/#define CIRCUITPY_BOOT_OUTPUT_FILE "/boot_out.txt"
```
skips the attempt in main.c to create an the boot_out.txt file.
It still looks like something is hanging up the filesystem when trying to create the boot_out.txt file.

**Comment by dhalbert** [comment]
I think I have a fix. In `main.c`, change this:
```
        #ifdef CIRCUITPY_BOOT_OUTPUT_FILE
        if (!skip_boot_output) {
            f_close(boot_output_file);
            filesystem_flush();
            boot_output_file = NULL;
        }
```
to this:
```
        #ifdef CIRCUITPY_BOOT_OUTPUT_FILE
        if (!skip_boot_output) {
            f_close(boot_output_file);
            filesystem_flush();
        }
        boot_output_file = NULL;       // This line moves outside the if
```
This is an error on my part :frowning: -- `boot_output_file` should have been set to NULL no matter what.  I changed it when I fixed the filesystem erase on power problems. What happened was that `code.py` output was being sent to `boot_out.txt` accidentally, though that variable was no longer valid.

Assuming this works for you, I'll file a PR.

**Comment by rhooper** [comment]
@dhalbert this appears to be a good fix!

**Comment by dhalbert** [comment]
It's an embarrassing bug on my part. I reworked that code for the power fix after a couple of long days. It has been broken for a while, but invisibly. Something about the recent merges made the garbage data in the file descriptor more likely to cause a hard fault.

**Comment by deshipu** [comment]
It was a pleasure to watch this debugging session, you guys rock!
